export const projects = [
  {
    name: "GEP COSTDRIVERS",
    position: "Frontend Developer",
    description:
      "Developed a SAAS platform using React, NextJS, Material UI, Zustand, and other libraries. The platform provides unique tools and detailed information on prices and costs across various segments, helping managers make strategic decisions.",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "NextJS",
      "Material UI",
      "Tailwind CSS",
      "Zustand",
      "Node.js",
      "vite",
      "Git",
      "GitHub",
      "REST APIs",
    ],
    url: "https://www.gep.com",
    image: {
      src: "/logo-gep.svg",
      alt: "GEP COSTDRIVERS",
    },
    imageBg: {
      src: "/bg-card-gep.png",
      alt: "GEP COSTDRIVERS",
    },
    startDate: "Nov 2023",
    endDate: "Present",
  },
  {
    name: "G&P",
    position: "Frontend Developer",
    description:
      "Worked on the 'Bolsa do Povo' project, a payment management platform for the state of São Paulo, Brazil. Utilized ReactJS, Vite, Styled-Components, and Context API for efficient state management and complex integrations with backend systems.",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Vite",
      "Styled-Components",
      "Node.js",
      "Git",
      "GitHub",
      "REST APIs",
    ],
    url: "https://www.gp.com.br",
    image: {
      src: "/logo-gp.svg",
      alt: "G&P",
    },
    imageBg: {
      src: "/bg-card-gp.png",
      alt: "G&P",
    },
    startDate: "May 2022",
    endDate: "Nov 2023",
  },
  {
    name: "Hi Platform",
    position: "Frontend Developer",
    description:
      "Developed a new institutional website for Hi Platform, focusing on chatbot integration solutions. Utilized ReactJS, NextJS, TypeScript, Styled-Components, and GSAP for animations. Ensured responsive design and optimized performance for various devices.",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "NextJS",
      "Styled-Components",
      "GSAP",
      "Node.js",
      "Git",
      "GitHub",
      "REST APIs",
    ],
    url: "https://www.hiplatform.com.br",
    image: {
      src: "/logo-hi.svg",
      alt: "Hi Platform",
    },
    imageBg: {
      src: "/bg-card-hi.png",
      alt: "Hi Platform",
    },
    startDate: "Apr 2021",
    endDate: "May 2022",
  },
  {
    name: "Flimed",
    position: "Software Engineer",
    description:
      "Contributed to the development of a management and control platform for medical activities, including appointment scheduling, telemedicine, and patient management. Utilized ReactJS, NodeJS, Redux, Styled-Components, and NextJS.",
    skills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Redux",
      "Styled-Components",
      "NextJS",
      "Git",
      "GitHub",
      "REST APIs",
    ],
    url: "https://www.flimed.com.br",
    image: {
      src: "/logo-flimed.svg",
      alt: "Flimed",
    },
    imageBg: {
      src: "/bg-card-flimed.png",
      alt: "Flimed",
    },
    startDate: "Aug 2020",
    endDate: "Apr 2021",
  },
];
