import type { Metadata } from "next";
import { Funnel_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const sciencePersonalUseOnly = localFont({
  src: "./fonts/SciencePersonalUseOnly-JpG37.otf",
  variable: "--font-science-personal-use-only",
});

const funnelSans = Funnel_Sans({
  weight: "400",
  variable: "--font-funnel-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelSans.variable} ${sciencePersonalUseOnly.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
